### ISSUE TITLE
Use $request->all()

### ISSUE THREAD

**Issue by mistikel** [nandajamban94/SPK-Penyakit-Ayam-broiler-dnegan-metode-SAW#1]
> $B0 = $request->get('nafsu_makan');
>         $B1 = $request->get('minum');
>         $B2 = $request->get('nafas');
>         $B3 = $request->get('diare');
>         $B4 = $request->get('bengkak_mata');
>         $B5 = $request->get('lendir');
>         $B6 = $request->get('kejang');
>         $B7 = $request->get('suhu_tubuh');
>         $arr_bobot = array($B0,$B1,$B2,$B3,$B4,$B5,$B6,$B7);

> $arr_bobot = $request->all()
Lebih simple

**Comment by nandapermana** [comment]
Makasih banyak. Aguusss
